### ISSUE TITLE
Input.py does not contain a check for number of inputs in each entry

### ISSUE THREAD

**Issue by anish-mudaraddi** [muon-spectroscopy-computational-project/muspinsim#11]
Currently when parsing an input file by running `params = MuSpinInput(open('test.in'))` no checks are made on number of inputs for each entry - thus it is possible to enter erroneous values like:
```
zeeman 1
    1 2 3 4
hyperfine 1 2
    1 2 3 4
    5 6 7
    8 9 10
orientation
    1 2 3 4 5
```

Subsequent checks when running the experiment by either running `ExperimentRunner(params)` or `FittingRunner(params)` will pick up the errors - but these may be harder to understand for the user. 

Ideally, since all keywords are expected to receive a fixed number of parameters per entry (except for spins) - we should have a check here and the specify line number of issue, number of parameters found and number of parameters expected

Additionally, these some of these checks are made in galaxy tool as well - but may not be necessary and can be removed if implemented here

**Comment by leandro-liborio** [comment]
What info do you need to add the check here?  In the description of the muspinsim parameters there is info about the features of each of them.
