### ISSUE TITLE
Memory Overflow errors for complex calculations

### ISSUE THREAD

**Issue by anish-mudaraddi** [muon-spectroscopy-computational-project/muspinsim#13]
running this file: 
```
name
 POM-ZF
spins
 mu 13e 13e 13e
dipolar 1 2
 3.82 6.85 2.0
dipolar 1 3
 3.92 -1.81 -8.3
dipolar 1 4
 -8.8 -1.81 -8.34
time
 range(0, 2.0, 500)
 ```
causes memory overflow to occur:

On Windows we run into the error:
```
Traceback (most recent call last):
  File "C:\Users\vgc59244\Miniconda3\envs\muonproject\Scripts\muspinsim-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Users\vgc59244\Miniconda3\envs\muonproject\lib\site-packages\muspinsim\__main__.py", line 78, in main
    runner.run()
  File "C:\Users\vgc59244\Miniconda3\envs\muonproject\lib\site-packages\muspinsim\experiment.py", line 278, in run
    dataslice = self.run_single(cfg)
  File "C:\Users\vgc59244\Miniconda3\envs\muonproject\lib\site-packages\muspinsim\experiment.py", line 335, in run_single
    data = H.evolve(self.rho0, cfg_snap.t, operators=[S])[:, 0]
  File "C:\Users\vgc59244\Miniconda3\envs\muonproject\lib\site-packages\muspinsim\hamiltonian.py", line 85, in evolve
    rho = np.exp(ll[None, :, :] * times[:, None, None]) * rho0[None, :, :]
numpy.core._exceptions.MemoryError: Unable to allocate 224. GiB for an array with shape (500, 5488, 5488) and data type complex128
```

is there anyway we can improve memory utilization here

**Comment by anish-mudaraddi** [comment]
This problem occurs because we are not making use of parrellization features using MPI.

Running the following on the same input file 
`mpirun -n 4 muspinsim.mpi input.in`

gives us another error 
```
Traceback (most recent call last):
  File "/home/vol08/scarf1108/muspinsim/bin/muspinsim.mpi", line 11, in <module>
    load_entry_point('muspinsim', 'console_scripts', 'muspinsim.mpi')()
  File "/home/vol08/scarf1108/repo/muspinsim/__main__.py", line 97, in main_mpi
    main(use_mpi=True)
  File "/home/vol08/scarf1108/repo/muspinsim/__main__.py", line 77, in main
    runner = ExperimentRunner(infile, {})
  File "/home/vol08/scarf1108/repo/muspinsim/experiment.py", line 47, in __init__
    mpi.broadcast_object(config)
  File "/home/vol08/scarf1108/repo/muspinsim/mpi.py", line 74, in broadcast_object
    v = self.comm.bcast(v, root=0)
  File "mpi4py/MPI/Comm.pyx", line 1569, in mpi4py.MPI.Comm.bcast
  File "mpi4py/MPI/msgpickle.pxi", line 721, in mpi4py.MPI.PyMPI_bcast
  File "mpi4py/MPI/msgpickle.pxi", line 147, in mpi4py.MPI.pickle_dump
  File "mpi4py/MPI/msgbuffer.pxi", line 50, in mpi4py.MPI.downcast
OverflowError: integer 2891401794 does not fit in 'int'
```

This error occurs when attempting to broadcast the `MuSpinConfig` object from root node to all other nodes. It does this by sequentially broadcasting the object's attributes.

When attempting to broadcast the `_system` attribute - which is another object `MuSpinSystem` we get this error.

Open MPI only allows broadcasting objects which are smaller than 2GB - and MuSpinSystem object is larger than 2GB for this calculation. 

** Solution **
We need to broadcast `MuSpinSystem` object to all nodes in chunks smaller than 2GB

**Comment by anish-mudaraddi** [comment]
Fixed issue with Open MPI: 
There was an issue broadcasting `MuSpinSystem` object -  this was likely due to an issue where each if it's `_terms` attribute contained a recursive defnition to the same `MuSpinSystem` object. 

Changed the logic to ignore the recursive definition and set the attribute after broadcasting - this seemed to have worked

But we still end up with the original error:
```
numpy.core._exceptions.MemoryError: Unable to allocate 224. GiB for an array with shape (500, 5488, 5488) and data type complex128
```

**Comment by anish-mudaraddi** [comment]
The numpy memory error is caused of this line: 
```
rho = np.exp(ll[None, :, :] * times[:, None, None]) * rho0[None, :, :]
```
specifically when `ll[None, :, :] * times[:, None, None]` is calculated we create a 3D numpy array which is too big to store in memory 

need to calculate this in smaller chunks if possible

**Comment by anish-mudaraddi** [comment]
running the file 
```
name
 POM-ZF
spins
 mu 13e 13e 13e 13e
dipolar 1 2
 3.82 6.85 2.0
dipolar 1 3
 3.92 -1.81 -8.3
dipolar 1 4
 -8.8 -1.81 -8.34
dipolar 1 5
 -8.8 -1.81 -8.34
time
 range(0, 2.0, 500)
```
causes a memory overflow error. Adding more spins requires exponentially more memory. 

The underlying problem is a limit on the amount of memory available to store the dense matrix describing spin operators in the system. 

When the experiment is run with the file mentioned, the program will create a `MuonSpinSystem` object - which would be used as a basis to run each experiment. 

During this process, it will calculate and store a set of `SpinOperator` objects for the muon. 

The more spins the system is required to simulate, the larger the numpy array `matrix` used to describe each SpinOperator needs to be. This matrix grows exponentially as we iteratively calculate a kronecker product for each operator against all other spins.

This puts a limit on the number of spins the system can model based on the amount of memory available 

This SpinOperator matrix seems to be very sparse - at least for this case. Therefore it could be viable to treat it as a sparse matrix. 

However, this matrix is used and manipulated in other calculations during the simulation process - such as to add interactions. These calculations may only work with a dense matrix - which we may not be able to change. 

Some things to consider:
1. Is it a common use-case to use complex spins like `13e`. How many spins are we likely to use.
2. Is it possible to treat spin operators as sparse matrices when doing calculations (thereby saving memory not storing null values)

**Comment by leandro-liborio** [comment]
Responses: 

1.  No: it is not very common to use 13e as spin.  However... This is not necessarily complex from the physical point of view.  Why is it that the size of the spin is a problem?  The number of spins really depends on the system that we are treating.  I would say that 10 is sort of a upper limit.
2. I think the answer to this is yes. Why don't we try

**Comment by joelvdavies** [comment]
Closing as mitigated with Celio's method as in https://github.com/muon-spectroscopy-computational-project/muspinsim/pull/19
