### ISSUE TITLE
Provide precompiled versions for major distributions

### ISSUE THREAD

**Issue by joelvdavies** [muon-spectroscopy-computational-project/muspinsim#24]
With the addition of pybind11/cython we need OS dependent pip wheels to avoid users needing to have a C++ compiler present on their system when installing via pip. [QuTiP](https://github.com/qutip/qutip) does this using a github workflow that builds versions for Windows, Ubuntu & macOS.

We can potentially use `auditwheel repair` to include OpenMP in the pip packages as well but this will need testing.

I believe the same should be possible with conda as QuTiP is also present there.

**Comment by elichad** [comment]
+1. There's a `pypa/cibuildwheel` GitHub Action available which may be easier to set up than writing the workflow manually - [example from spglib](https://github.com/spglib/spglib/blob/develop/.github/workflows/pypi-wheel-builds.yml)

**Comment by joelvdavies** [comment]
Closed with #35
